### ISSUE TITLE
`jwt` key not being retrieved from context

### ISSUE THREAD

**Issue by yargevad** [goware/jwtauth#10]
It's entirely possible I'm doing something wrong, but I can't see it. The parsed jwt data is there when I dump out the context with `%+v`, but it's not coming back from `ctx.Value`. Building and running this example, then hitting `localhost:8080` in the browser will dump the context to `stderr` with `%+v`, and write the specific error to the browser.

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/dgrijalva/jwt-go"
	"github.com/goware/jwtauth"
	"github.com/pressly/chi"
)

var TokenAuth *jwtauth.JwtAuth

func init() {
	TokenAuth = jwtauth.New("HS256", []byte("fooo"), nil)
}

func main() {
	r := chi.NewRouter()
	r.Get("/", Authenticate)
	r.Group(func(r chi.Router) {
		r.Use(TokenAuth.Verifier)
		r.Use(jwtauth.Authenticator)
		r.Route("/foo", func(r chi.Router) {
			r.Get("/", FooIndex)
		})
	})

	log.Fatal(http.ListenAndServe(":8080", r))
}

func Authenticate(w http.ResponseWriter, r *http.Request) {
	cl := jwtauth.Claims{}.
		SetExpiryIn(time.Hour*24).
		SetIssuedNow().
		Set("uid", 13)
	_, str, err := TokenAuth.Encode(cl)

	if err != nil {
		http.Error(w, http.StatusText(500), 500)
	}
	c := &http.Cookie{Name: "jwt", Value: str}
	http.SetCookie(w, c)
	w.Header().Set("Location", "/foo")
	w.WriteHeader(http.StatusFound)
}

func FooIndex(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	fmt.Fprintf(os.Stderr, "%+v\n", ctx)
	token, ok := ctx.Value("jwt").(*jwt.Token)
	if !ok {
		fmt.Fprintln(os.Stderr, "no auth context available!")
		http.Error(w, "no auth context available", 404)
		return
	} else if token == nil {
		http.Error(w, "no token available", 404)
		return
	} else if !token.Valid {
		http.Error(w, "invalid token", 403)
		return
	}

	fmt.Fprintf(os.Stderr, "%+v\n", token)
	// this cast & check is no longer necessary after vendoring jwt-go 2.7.0
	claims, ok := token.Claims.(jwt.MapClaims)
	if !ok {
		http.Error(w, "can't cast claims", 422)
		return
	}

	// claims => token.Claims after vendoring jwt-go 2.7.0
	uid, ok := claims["uid"].(float64)
	if !ok {
		http.Error(w, "no user available", 404)
		return
	}

	fmt.Fprintf(w, "user found (%d)", uid)
}
```

**Comment by bradleyfalzon** [comment]
If you don't correctly type assert the token by removing the `ok` check, eg:

```
   52 func FooIndex(w http.ResponseWriter, r *http.Request) {
   53     ctx := r.Context()
   54     spew.Dump(ctx.Value("jwt"))
   55     var ok = true
   56     token := ctx.Value("jwt").(*jwt.Token)
   57     if !ok {
...
```

You get an interesting panic: 
```
(*jwt.Token)(0xc420062870)({
 Raw: (string) (len=140) "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzM4MzM4NjIsImlhdCI6MTQ3Mzc0NzQ2MiwidWlkIjoxM30.2-kOSbYyWNAJ2KEBrfxLqrRKY0C9mNopsq6VFzm05hI",
 Method: (*jwt.SigningMethodHMAC)(0xc4200d4820)({
  Name: (string) (len=5) "HS256",
  Hash: (crypto.Hash) 5
 }),
 Header: (map[string]interface {}) (len=2) {
  (string) (len=3) "alg": (string) (len=5) "HS256",
  (string) (len=3) "typ": (string) (len=3) "JWT"
 },
 Claims: (map[string]interface {}) (len=3) {
  (string) (len=3) "exp": (float64) 1.473833862e+09,
  (string) (len=3) "iat": (float64) 1.473747462e+09,
  (string) (len=3) "uid": (float64) 13
 },
 Signature: (string) (len=43) "2-kOSbYyWNAJ2KEBrfxLqrRKY0C9mNopsq6VFzm05hI",
 Valid: (bool) true
})
2016/09/13 16:31:09 http: panic serving 127.0.0.1:50206: interface conversion: interface {} is *jwt.Token, not *jwt.Token
```

**Comment by yargevad** [comment]
Thanks @bradleyfalzon, that's due to a mismatch between the version of `jwt-go` that `jwtauth` vendors, and what I was using (latest, unvendored). Vendoring the same version as `jwtauth` and removing a no-longer-necessary cast unfortunately lands me back at the same issue.

**Comment by pkieltyka** [comment]
ah yes, that would do it. jwtauth latest stable doesn't support jwt-go v3.0

I will update the README right now to note jwtauth requires https://github.com/dgrijalva/jwt-go/tree/v2.7.0 and that there is a PR here https://github.com/goware/jwtauth/pull/8 for jwt-go v3.0 support

TBH, jwt-go made some poor design decisions about its code structure, which I think some of its been improved, but this is the reason I wasn't rushing to get to the latest version.

**Comment by pkieltyka** [comment]
@yargevad is your example in the first post working now?

**Comment by yargevad** [comment]
Unfortunately not, it's still hitting the `no auth context available!` case.

**Comment by pkieltyka** [comment]
Okay, thanks. I'll check it out in a few minutes and get back to you.

**Comment by pkieltyka** [comment]
@yargevad can you try to run https://github.com/goware/jwtauth/blob/master/_example/main.go ? I just whipped this up and it works great. As well, what happens if you run: go test -v in the project? the tests should pass as well.

**Comment by yargevad** [comment]
Looks like this was entirely due to the vendoring errors on my part. The newer package was still being used.

Thanks for the sanity check & sorry for the noise!

**Comment by pkieltyka** [comment]
no problem at all, thanks for helping me fix the docs! best regards.

**Comment by DiknT** [comment]
as a note hoping to save others from some headache, I was having the same error:
http: panic serving 127.0.0.1:50206: interface conversion: interface {} is *jwt.Token, not *jwt.Token

Only vendoring dgrijalva/jwt-go@2.7.0 didn't solve this, I also had to vendor this package itself, i.e. goware/jwtauth

As I am new to go I am not sure if this is intended or some packaging or vendoring error...
Anyway, thx for this package 👍

**Comment by pkieltyka** [comment]
@DiknT thanks for the note and no prob!
