### ISSUE TITLE
Change the jwt package

### ISSUE THREAD

**Issue by diegobernardes** [goware/jwtauth#13]
Take a look at https://jwt.io/
Whould be nice to change the jwt package to use github.com/SermoDigital/jose.

**Comment by pkieltyka** [comment]
Can you elaborate as to why switch from current jwt-go?

**Comment by diegobernardes** [comment]
I'm sorry for the hype, was a unnecessary ticket.
It's my first time using jwt, was reading about it and when i got into the claims, realized that most of the claims are not implemented in current package, this was why i suggest the move, but they are all optional and isn't that hard to implement.

https://tools.ietf.org/html/rfc7519#section-4.1
