### ISSUE TITLE
interface conversion: interface {} is *jwt.Token, not *jwt.Token

### ISSUE THREAD

**Issue by diegobernardes** [goware/jwtauth#14]
I'm getting a very strange error using the sample code from jwtauth. The error is at this line:

```golang
token := ctx.Value("jwt").(*jwt.Token)
```

Solved this issue after remove the vendor folder inside jwtauth project.

Keeping the vendor in a library project isn't a good idea, its better to remove it, the front page of the project has a very big warning about the dependency, its better to handle the dependencies at the application level.

**Comment by advanderveer** [comment]
Yes, this is confusing. @see my comment here: #9

**Comment by VojtechVitek** [comment]
@diegobernardes are you using Glide, as in #9? (see my comment https://github.com/goware/jwtauth/pull/9#issuecomment-278968090 pls)

This project has test that imports jwt-go. We can't just remove it.

**Comment by pkieltyka** [comment]
I suggest to use govendor

**Comment by adelowo** [comment]
Go seriously needs a dependency manager though.. Thanks a lot to everyone who figured this out
